In [ ]:
# 특정 시점의 상장 종목코드 조회 가능

In [1]:
from pykrx import stock

In [3]:
tickers = stock.get_market_ticker_list()

In [5]:
tickers = stock.get_market_ticker_list('2010-01-01')

In [2]:
stock.get_market_fundamental("20200101", "20200430", "005930", freq="m")

              BPS   PER   PBR   EPS   DIV   DPS
날짜
2020-01-31  35342  8.54  1.56  6461  2.57  1416
2020-02-29  35342  8.85  1.62  6461  2.48  1416
2020-03-31  35342  8.51  1.56  6461  2.57  1416
2020-04-30  35342  7.09  1.30  6461  3.09  1416

In [ ]:
stock.get_market_fundamental("20200101", "20200430", "005930", freq="m")

In [6]:
df = stock.get_market_trading_value_by_date("20231001", "20231104", "005930")
print(df.head())

                    기관합계        기타법인            개인         외국인합계  전체
날짜
2023-10-04  -85888536200  4030278000  205368934600 -123510676400   0
2023-10-05   24466732800  3391043300  202145558600 -230003334700   0
2023-10-06   55864006600  1691952500  223999980000 -281555939100   0
2023-10-10  241278636200  2404889700  -15275672400 -228407853500   0
2023-10-11  205910450200 -2593431500 -233681005400   30363986700   0

In [7]:
df

                    기관합계        기타법인            개인         외국인합계  전체
날짜
2023-10-04  -85888536200  4030278000  205368934600 -123510676400   0
2023-10-05   24466732800  3391043300  202145558600 -230003334700   0
2023-10-06   55864006600  1691952500  223999980000 -281555939100   0
2023-10-10  241278636200  2404889700  -15275672400 -228407853500   0
2023-10-11  205910450200 -2593431500 -233681005400   30363986700   0
2023-10-12   51824399000  -472600400  -23625252700  -27726545900   0
2023-10-13   -2362710400  1189642900   51277945000  -50104877500   0
2023-10-16    2892011500  -672547700   73628845100  -75848308900   0
2023-10-17  -92508181100 -4087417900 -228334046600  324929645600   0
2023-10-18     338795300 -1920612200 -342157222000  343739038900   0
2023-10-19  -49378047000  1424142200   -9806086900   57759991700   0
2023-10-20  -58688545000 -4833265300   17655526700   45866283600   0
2023-10-23   53550479000  2953353100   32858962800  -89362794900   0
2023-10-24  -18709923400  5736432700   41340697900  -28367207200   0
2023-10-25    3999682000 -7889001500   37852421900  -33963102400   0
2023-10-26   -5125712300  -609440600   98048357500  -92313204600   0
2023-10-27   54155950500 -1067433700    9255298100  -62343814900   0
2023-10-30   43541758400  -884030100  -13798263600  -28859464700   0
2023-10-31    4173106700  5060066200   15764945700  -24998118600   0
2023-11-01  150786315400 -2491912900 -151963265200    3668862700   0
2023-11-02   14868527500 -2936002600 -208904622200  196972097300   0
2023-11-03    1059675700   485483800  -89117201200   87572041700   0